apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-demo

spec:
  replicas: 5

  selector:
    matchLabels:
      app: devsecops-demo

  template:
    metadata:
      labels:
        app: devsecops-demo

    spec:
      containers:
      - name: devsecops-demo
        image: dineshjanaparapu/devsecops-demo:6
        ports:
        - containerPort: 8080
